services:
  mongo_db:
    image: mongo
    container_name: adminjs-example-mongo
    ports:
      - "27017:27017"

  postgres_db:
    image: postgres:14
    container_name: adminjs-example-postgres
    environment:
      POSTGRES_DB: adminjs
      POSTGRES_USER: adminjs
      POSTGRES_PASSWORD: adminjs
    ports:
      - "5432:5432"

  mysql_db:
    image: mysql:8
    container_name: adminjs-example-mysql
    environment:
      MYSQL_DATABASE: adminjs
      MYSQL_USER: adminjs
      MYSQL_PASSWORD: adminjs
      MYSQL_ROOT_PASSWORD: adminjs
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      retries: 10

  app:
    build: .
    container_name: adminjs-app
    depends_on:
      mysql_db:
        condition: service_healthy
      postgres_db:
        condition: service_started
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql://adminjs:adminjs@mysql_db:3306/adminjs
      MIKRO_ORM_CLIENT_URL: postgres://adminjs:adminjs@postgres_db:5432/adminjs
